### ISSUE TITLE
Log and Seed Drops are not balanced

### ISSUE THREAD

**Issue by Gaelmare** [Gaelmare/dynamictreestfc#12]
Too few logs, too many seeds?

**Comment by Gaelmare** [comment]
Change harvestMultiplier in DT config to about 1.5 to balance better.

**Comment by SeriousCreeper** [comment]
Is there anything that can be done about too many seeds? Seems like a tree drops quite a few. I thought about using something like "Dropt" to change the chance of a seed dropping (and increase it when using an axe/scythe), but figured i'll see first if there is a built-in way already (or coming)

**Comment by Gaelmare** [comment]
Only what's in the generic DT configs. Can't recall off the top of my head.

**Comment by SeriousCreeper** [comment]
Seems like it only has an option for seeds randomly falling off leaves when the tree is alive, but nothing for actual drops when chopping it down. I'll try to find a work around!
