### ISSUE TITLE
Leaves prevent player passage

### ISSUE THREAD

**Issue by madflavius** [Gaelmare/dynamictreestfc#14]
Leaves prevent players from passing through them (vanilla TFC TNG behavior). Not sure if this is an intended change or bug.

Mod Versions:
TFC 1.12-0.29.0.115
dynamictreestfc-0.9
DynamicTrees-1.12.2-0.9.7

**Comment by Gaelmare** [comment]
This is controllable in the DT config file.

**Comment by madflavius** [comment]
Oh, I'm sorry. I didn't see that config option.
