### ISSUE TITLE
TFC Dynamic Trees rooty soils don't convert back into TFC soils.

### ISSUE THREAD

**Issue by UnlimatedStone9** [Gaelmare/dynamictreestfc#18]
They convert into vanilla soils.

If it's a limitation of Dynamic Trees, and last I saw it was (from DT BOP), there are addons that fix it for themselves. Like Dynamic Trees Natura.

**Comment by Gaelmare** [comment]
Is this with the most recent version, and on a tfc world?

**Comment by UnlimatedStone9** [comment]
You said DT-TFC uses its own rooty soil? If so I'm closing this.
If the issue persists I'll open it again, or you can if you notice it happen. Although it's not DT-TFC's fault natively. :p
