### ISSUE TITLE
Rooty soil should render as grass when grass is near it and not dirt?

### ISSUE THREAD

**Issue by UnlimatedStone9** [Gaelmare/dynamictreestfc#19]
![image](https://user-images.githubusercontent.com/40124890/77232347-67dd9f80-6b98-11ea-951f-20402f2b5c28.png)
This isn't appealing, it would make sense if it displayed as grass when connected to other grasses.

**Comment by UnlimatedStone9** [comment]
Okay I tested the soils from DTNatura, it's still vanilla dirt, so that assumption was wrong. DT likely needs to fix this itself, or allow not using rooty soils.

**Comment by Gaelmare** [comment]
This is an issue with dttfc. Not sure how I'm going to fix it yet. There's an IMimic interface the DT rooty soil uses, but it's not right for tfc. Thanks for asking! Right now, immature dttfc trees spawn on a rooty andesite dirt block.

**Comment by Gaelmare** [comment]
Fixed as of https://github.com/Gaelmare/dynamictreestfc/pull/38 not yet released.
