### ISSUE TITLE
"Vanilla" dynamic seeds?

### ISSUE THREAD

**Issue by drago87** [Gaelmare/dynamictreestfc#20]
Would it be possible to make it so that "vanilla" dynamic seeds can be placed on TFC dirt? (and the cactus on sand) as well as the outher addon's seeds? or is that something the "vanilla" dynamic tree's mod need to do?

**Comment by Lgmrszd** [comment]
Vanilla and other addon's seeds works fine on TFC grass (as for the latest version). Vanilla cactus seed, however, is not plant-able on TFC sand types but on TFC dirt, and will convert rooty soil into sand upon harvesting.

**Comment by Gaelmare** [comment]
This should be fixed.
