### ISSUE TITLE
Tree saplings grow very fast

### ISSUE THREAD

**Issue by Zekryl** [Gaelmare/dynamictreestfc#23]
If i place nearby a lot of saplings they start growing very fast for some reason. 

I use last version of addon.

Here is video with example - https://youtu.be/OWbBuOd0GZY

**Comment by Gaelmare** [comment]
I've just tested this with the latest version. One sapling by itself doesn't seem to grow on average any slower than a group of saplings together.

**Comment by Gaelmare** [comment]
Closing, stale issue with no feedback.
