### ISSUE TITLE
Can’t plant saplings from other addons in TFC soils 

### ISSUE THREAD

**Issue by supermassimo** [Gaelmare/dynamictreestfc#27]
This issue was posted in the Extra Compat repository but I’m moving it here as I think it’s more appropriate.
https://github.com/supermassimo/DynamicTrees-ExC/issues/42

Comment from me:
Solution is easy, You can check how my The Aether addon registers Aether soil for every tree in registry that allows grass. The BoP addon also does this.

Op posted:
Other Dynamic Trees addons seem to work 💯 percent fine though.

**Comment by agilmore2** [comment]
Thanks. I believe I already fixed and released for this problem, see commit https://github.com/Gaelmare/dynamictreestfc/commit/861fd6ca409599eb25b08436bf83e5c430765003

So, this issue could use an update.

**Comment by Gaelmare** [comment]
This one is already fixed and released, see commit https://github.com/Gaelmare/dynamictreestfc/commit/861fd6ca409599eb25b08436bf83e5c430765003

Could use an update from the original reporter. @Royal-Jelly

**Comment by Royal-Jelly** [comment]
I am in fact using the absolute latest version of dynamictreestfc which has is working as intended.

its @supermassimo and his addons in which are not planting well on other soil types.

**Comment by Royal-Jelly** [comment]
Also ... sorry for unintentionally for wasting your time @Gaelmare, thank you for helping me clear up this misunderstanding.

**Comment by Gaelmare** [comment]
No Problem. The DTTFC addon registers TFC soils to every registered DT species. If the saplings aren't working, it could be that they weren't registered when the registerBlocks function was called in DTTFC. It may be an addon ordering issue. Not sure if that's the right time is to register additional acceptableSoil blocks?

**Comment by Royal-Jelly** [comment]
I was toying around with modlists and actually found something interesting @Gaelmare even without your DTTFC mod i have planted some addon trees on tfc soils
