### ISSUE TITLE
[Bug] TFC Dynamic Trees aren't cut down properly

### ISSUE THREAD

**Issue by Alex33212** [Gaelmare/dynamictreestfc#29]
Using Dynamic Trees ver. 0.9.15 and DynamicTreesTFC ver. 0.9.14 (both the latest at time of writing), I've found that there's some very weird behavior when trying to cut down trees added by this patch, though not vanilla trees. Specifically, in creative, destroying a tree's trunk has no effect, and the removed block instantly reappears. In survival, the same thing happens, though the tree properly falls after a few seconds. Additionally, once the fallen tree disappears, there's a similar delay in the harvested wood & sticks appearing.

**Comment by Gaelmare** [comment]
So the issue is in creative? The lag in survival is known.

**Comment by Gaelmare** [comment]
Creative mode now insta-chops. Thanks for the bug report!
