### ISSUE TITLE
Chopping down trees converts the block beneath to vanilla dirt instead of the tfc dirt as of DT-0.9.21 & DTtfc-0.9.15

### ISSUE THREAD

**Issue by velocityraptor-real** [Gaelmare/dynamictreestfc#34]
When a dynamic tree gets big enough to convert it's block underneath to a rooty block and then gets chopped down, the block turns into vanilla dirt instead of the standard tfc version.

F.e: I chop down my hickory tree and the block that was underneath it isn't shale dirt, rather vanilla dirt.

**Comment by Gaelmare** [comment]
I know. This is a regression as it used to only happen sometimes, and now happens all the time. I know how to solve, but don't have the time right now to publish an update. Plus, Curseforge is currently read-only for a bit.

Duplicate of #32
