### ISSUE TITLE
.gitignore and gradle weirdness

### ISSUE THREAD

**Issue by eerussianguy** [Gaelmare/dynamictreestfc#36]
Of course everyone hates gradle and the most important thing is that the setup works on the main dev's computer before anyone else's but i noticed a couple things that caused issues setting up the workspace:

- /gradle/ is gitignored presumably by accident, which is necessary to import the project and can't be generated on it's own
- the deps folder is designated one level up in the filetree (so in my idea projects folder rather than the project folder for DTTFC) which causes some weirdness, mainly that you can't runClient in dev (models will fail to load) and I also needed to put TFC in a /libs/ folder in the main dev environment in order to get it's classes to be recognized

**Comment by Gaelmare** [comment]
Thanks EER!

 I'll get that gradle thing fixed. I was working on multuple DT projects and put the dep there. My apologies. I definitely had runClient working.

I don't like shipping a TFC build, so encourage a deobf download into the libs folder on setup.
