### ISSUE TITLE
DT Ignores TFC Axe Damage Model

### ISSUE THREAD

**Issue by Xamllew** [Gaelmare/dynamictreestfc#37]
TFC calculates the amount of damage your axe takes depending on the size of the tree you chop down. IMO as it stands, without this feature axes beyond stone axe are somewhat pointless as a stone axe lasts quite a while.

**Comment by agilmore2** [comment]
Oh, that reminds me. I need to apply that 60% yield model for TFC stone axes. ;)

If the damage change bothers you, change the DT setting axeDamageMode to 2.

**Comment by Gaelmare** [comment]
Oh, that reminds me. I need to apply that 60% yield model for TFC stone axes. ;)

If the damage change bothers you, change the DT setting axeDamageMode to 2.
