### ISSUE TITLE
Leaves don't fall out

### ISSUE THREAD

**Issue by SpeeeDCraft** [Gaelmare/dynamictreestfc#43]
Forge: 2855
TFC: 1.7.11.169
Dynamic Trees: 0.9.21
Dynamic Trees TFC: 0.9.16 

When cutting down the foliage with scissors, nothing falls out

**Comment by Gaelmare** [comment]
Yes. DT changes the relationship between trees and saplings. If you want new trees, pick up the seeds that fall when you chop it down.
