### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by SpeeeDCraft** [Gaelmare/dynamictreestfc#46]

**Comment by MagmaBro123** [comment]
Bet so. You or someone else might as well continue it. @Gaelmare delete if you won't continue it.

**Comment by Gaelmare** [comment]
no, the project isn't dead at all. As stated on the CF page, "Please see the TFC:TNG discord at https://invite.gg/terrafirmacraft in channel #tng-addons for support.  "
