### ISSUE TITLE
translations for seeds are missing

### ISSUE THREAD

**Issue by Gaelmare** [Gaelmare/dynamictreestfc#9]

**Comment by And3r16Gaming** [comment]
text.dynamictreestfc/douglas_fir.name=Douglas Fir Cone
text.dynamictreestfc/white_elm.name=White Elm Seed
text.dynamictreestfc/acacia.name=Acacia Seed
text.dynamictreestfc/ash.name=Ash Key
text.dynamictreestfc/aspen.name=Aspen Catkin
text.dynamictreestfc/birch.name=Birch Catkin
text.dynamictreestfc/chestnut.name=Chestnut Seed
text.dynamictreestfc/hickory.name=Hickory Nut
text.dynamictreestfc/kapok.name=Kapok Pod
text.dynamictreestfc/maple.name=Maple Seed
text.dynamictreestfc/oak.name=Oak Acorn
text.dynamictreestfc/pine.name=Pine Cone
text.dynamictreestfc/spruce.name=Spruce Cone
text.dynamictreestfc/white_cedar.name=White Cedar Seed
text.dynamictreestfc/willow.name=Willow Seed
text.dynamictreestfc/sycamore.name=Sycamore Key
text.dynamictreestfc/sequoia.name=Sequoia Cone
text.dynamictreestfc/rosewood.name=Rosewood Seed
text.dynamictreestfc/blackwood.name=Blackwood Seed
text.dynamictreestfc/palm.name=Palm Pod
